[package]
name = "rust-warp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0"
serde_json = "1.0"
mongodb = "2.1"
futures = "0.3"
async-trait = "0.1"
user-persist = { path = "../user-persist" }

[dependencies.tracing]
version = "0.1"
features=["log"]

[dependencies.tracing-subscriber]
version = "0.3"
default-features = true
features = ["json", "env-filter", "fmt"]

[dependencies.clap]
version = "3.0"
features = ["derive"]

[dependencies.uuid]
version = "0.8"
features = ["v4"]

[dependencies.warp]
version = "0.3"
features = ["tls", "compression-gzip"]

[dependencies.tokio]
version = "1"
features = ["full"]