[package]
name = "rust-axum"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
# [[bin]]
# name = "rust-axum"

# [lib]

[dependencies]
user-persist = { path = "../user-persist" }
thiserror = "1"
serde = "1"
mongodb = "2"
tracing = "0.1"
http = "0.2"
http-body = "0.4"
serde_json = "1"
async-trait = "0.1"
jsonwebtoken = "8"
tower-layer = "0.3"
chrono = "0.4"
futures = "0.3"
sha2 = "0.10"
base64 = "0.13"
axum-macros = "0.3"

[dependencies.tower]
version = "0.4"
features = ["full"]

[dependencies.hyper]
version = "0.14"
features = ["full"]

[dependencies.clap]
version = "3"
features = ["derive", "color", "suggestions", "wrap_help"]

[dependencies.axum]
version = "0.6"
features = ["headers", "tower-log"]

[dependencies.axum-server]
version = "0.4"
features = ["tls-rustls"]

[dependencies.tower-http]
version = "0.3"
features = ["full"]

[dependencies.tracing-subscriber]
version = "0.3"
default-features = false
features = ["json", "env-filter", "std", "ansi", "fmt"]

[dependencies.uuid]
version = "1"
features = ["v4"]

[dependencies.tokio]
version = "1"
features = ["full"]
