[package]
name = "rust-axum"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.4"
user-persist = { path = "../user-persist" }
thiserror = "1.0"
serde = "1.0"
mongodb = "2.1"
clap = "3.0"
tracing = "0.1"
http = "0.2"
serde_json = "1.0"
async-trait = "0.1"
jsonwebtoken = "8.0"
axum-macros = "0.1"
tower = "0.4"

[dependencies.tower-http]
version = "0.2"
features = ["full"]

[dependencies.axum-server]
version = "0.3"
features = ["tls-rustls"]

[dependencies.validator]
version = "0.14"
features = ["derive"]

[dependencies.tracing-subscriber]
version = "0.3"
default-features = false
features = ["json", "env-filter", "std", "ansi", "fmt"]

[dependencies.uuid]
version = "0.8"
features = ["v4"]

[dependencies.openssl]
version = "0.10"
features = ["v110"]

[dependencies.tokio]
version = "1.16"
features = ["time"]
